### PR TITLE
Refactor/extract htmlgen methods to wrapper class

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR:
- Moves all direct calls to python2's HtmlGen to a wrapper class
- Cleans up some pylint errors

#### Any background context you want to provide

- Isolating HtmlGen calls to a wrapper class makes testing easier, so in the migration branch, moving to python3-htmlGen will be easier with no surprises
- Broke this to a separate PR to avoid making the migration branch too big

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
@zsloan could you have a look at this? It's good to go imo. I've only ran Mechanical Rob for this one. In the Python3 branch, I'll only replace the methods in the wrapper class.

**Comment by zsloan** [comment]
I'm getting this error (I think the issue is that the create_image_tag
function currently requires an "alt" parameter):

      GeneNetwork tux01:gene:2.11-rc2-HEAD-68f05d7f8
http://gn2-zach.genenetwork.org/run_mapping ( 5:55PM UTC Aug 24, 2020)
       Traceback (most recent call last):
         File "/usr/local/guix-profiles/gn-latest-20200811/lib/python2.7/site-packages/flask/app.py",
line 1950, in full_dispatch_request
           rv = self.dispatch_request()
         File "/usr/local/guix-profiles/gn-latest-20200811/lib/python2.7/site-packages/flask/app.py",
line 1936, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/export/local/home/zas1024/gn2-zach/gene/wqflask/wqflask/views.py",
line 793, in mapping_results_page
           gn1_template_vars =
display_mapping_results.DisplayMappingResults(result).__dict__
         File "/export/local/home/zas1024/gn2-zach/gene/wqflask/wqflask/marker_regression/display_mapping_results.py",
line 551, in __init__
           border="0", usemap='#WebQTLImageMap'
       TypeError: create_image_tag() takes exactly 2 arguments (1 given)

**Comment by BonfaceKilz** [comment]
You are right. Thanks for catching that. Let me push the change, and resolve the merge conflict

**Comment by BonfaceKilz** [comment]
@zsloan https://github.com/genenetwork/genenetwork2/pull/425/commits/d18f24281a30759f4fbafe3e50d383438f38e2de fixes it

**Comment by BonfaceKilz** [comment]
@zsloan this is ready to merge. Wdyt?

**Pull request merged**
