### PR TITLE
write datasets to text files

### PR DESCRIPTION
**Pull request by Alexanderlacuna**

### CODE REVIEW

**Comment by Alexanderlacuna** [comment]
@fredmanglis this is ready for review the  only  issue is that am storing the text files in /tmp directory which might 
not be that persistent  .GN1 stores the textfiles  in  /gnshare/gn directory am not sure if this is a thing in gn2 maybe  @zsloan

**Comment by zsloan** [comment]
We can just create a directory for these files (in /tmp or elsewhere) and maybe have it passed in as one of the environment variables (like we do the genotype directory)?

**Review by fredmanglis — COMMENTED** [review]
:+1:

**Comment by fredmanglis** [comment]
> ... the only issue is that am storing the text files in /tmp directory which might not be that persistent  ...

Well, that is not too much of a problem, since the files can be auto-regenerated with your work, right?

A bigger problem is the text-files going stale: if the dataset, or specific traits within a dataset are updated, the data in the file(s) is effectively out of date (I think).

This is a much bigger problem, and I think some of the versioning work that @BonfaceKilz or @arunisaac are working on will come in handy, or might actually be directly related to this.

In any case, I think this is good to go, and the extra concerns can be dealt with by and by.

**Comment by zsloan** [comment]
Yeah, updates are an issue, but fortunately the vast majority of ProbeSet
datasets are never updated (it's more of a problem for phenotypes).

**Comment by fredmanglis** [comment]
@Alexanderlacuna I have merged your work and pushed it.

**Comment by Alexanderlacuna** [comment]
> We can just create a directory for these files (in /tmp or elsewhere) and maybe have it passed in as one of the environment variables (like we do the genotype directory)?

that would  be  better to make  everything well organized

**Comment by Alexanderlacuna** [comment]
> > ... the only issue is that am storing the text files in /tmp directory which might not be that persistent  ...
> 
> Well, that is not too much of a problem, since the files can be auto-regenerated with your work, right?
> 
> A bigger problem is the text-files going stale: if the dataset, or specific traits within a dataset are updated, the data in the file(s) is effectively out of date (I think).
> 
> This is a much bigger problem, and I think some of the versioning work that @BonfaceKilz or @arunisaac are working on will come in handy, or might actually be directly related to this.
> 
> In any case, I think this is good to go, and the extra concerns can be dealt with by and by.

Yeah  if am not wrong the /tmp  directory  is deleted weekly. we  could also solve this by having date of  last modified for tables  as  a hash    included in the filename

**Pull request merged**
