### PR TITLE
Feature/integrate feed analyzer

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR adds code to read code from the REDIS queues that contain the scored tweets. For now, it display 15 tweets; we could always tweak it to read more

#### How should this be tested

The test server will be shared later in the comments section

#### Any background context you want to provide

N/A

#### What are the relevant pivotal tracker stories

https://github.com/genenetwork/genenetwork2/issues/400

#### Screenshots (if appropriate)

N/A

#### Questions

N/A

### CODE REVIEW

**Comment by pjotrp** [comment]
Thanks, I'll have a look soon.

**Comment by pjotrp** [comment]
Hi @BonfaceKilz: Let's make the voting page 3 columns. One news sorted by time stamp. One non-news (e.g. github updates) sorted by time stamp. And then a list ranked by votes and time stamps - that is anything voted up gets listed there and we show them by time stamp - which is the final list of what we'll see on the main website.

People can vote up/down and mark for deletion on any of these lists. For now, I'll be the one who actively deletes by running a script on the redis server. Can you implement that?

**Comment by BonfaceKilz** [comment]
Yeah, that's implementable :+1:

**Comment by pjotrp** [comment]
There are too many commits in this branch. What are we going to do about that? I think we should merge asap.

**Comment by zsloan** [comment]
If you're referring to the list of 38 commits, most of those are on
production already. I'm not sure why those ended up included alongside the
tweet feed stuff.

**Comment by BonfaceKilz** [comment]
@zsloan's that's because I did a rebase to sync with the testing branch.

**Comment by BonfaceKilz** [comment]
@pjotrp let's merge this once the python3 migration branch has been merged. Wdyt?

**Comment by BonfaceKilz** [comment]
Will re-open this in a smaller PR. I'll cherry-pick commits here later.

**Pull request closed without merging**
