### PR TITLE
Feature/display svg graph of deps

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR adds an SVG graph of python3 deps.

#### How should this be tested?

See (set up temporarily): http://gn2-test1.genenetwork.org/environments/

#### Any background context you want to provide?

Associated channel changes are [here](http://gn2-test1.genenetwork.org/environments/).

The SVG file appears squashed, but I can't think of a way around that. I reckon since you could view the image in a separate window, imho it LGTM.

#### What are the relevant pivotal tracker stories?

N/A

#### Screenshots (if appropriate)

N/A
#### Questions

N/A

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
Ping @pjotrp. I've added the svg. Have a look at it [here](http://gn2-test1.genenetwork.org/environments/). It's squashed though.

**Comment by pjotrp** [comment]
On Sun, Dec 06, 2020 at 05:05:52AM -0800, BonfaceKilz wrote:
>    Ping [1]@pjotrp. I've added the svg. Have a look at it [2]here. It's
>    squashed though.

Perfect. You may add text that says something like

  To explore this image SVG you may want to open it in new browser page and
  zoom in. Or use an SVG viewing application.

The reason we want it there is that people can use it for publications
etc.

**Comment by BonfaceKilz** [comment]
Pjotr Prins <notifications@github.com> writes:

> On Sun, Dec 06, 2020 at 05:05:52AM -0800, BonfaceKilz wrote:
>>    Ping [1]@pjotrp. I've added the svg. Have a look at it [2]here. It's
>>    squashed though.
>
> Perfect. You may add text that says something like
>

Done.

>   To explore this image SVG you may want to open it in new browser page and
>   zoom in. Or use an SVG viewing application.
>
> The reason we want it there is that people can use it for publications
> etc.

This makes sense.

-- 
Bonface M. K. <https://www.bonfacemunyoki.com>
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz
GPG Key: D4F09EB110177E03C28E2FE1F5BBAE1E0392253F

**Comment by BonfaceKilz** [comment]
Going ahead to merge this after adding the description mentioned above :tada:

**Pull request merged**
