### PR TITLE
rust correlation integration

### PR DESCRIPTION
**Pull request by Alexanderlacuna**
pr deals with integrating rust correlation code

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
*nitpick:* "init:perform top n sample for probes" the commit could be a
bit more useful/definitive.  It makes it easier on me when I look at
your work.


---
 .../wqflask/correlation/rust_correlation.py   | 124 +++++++++++++++++-
 1 file changed, 119 insertions(+), 5 deletions(-)

diff --git a/wqflask/wqflask/correlation/rust_correlation.py b/wqflask/wqflask/correlation/rust_correlation.py
index 3628f5493..94720f547 100644
--- a/wqflask/wqflask/correlation/rust_correlation.py
+++ b/wqflask/wqflask/correlation/rust_correlation.py
@@ -1,6 +1,9 @@
 """module contains integration code for rust-gn3"""
 import json
 from functools import reduce
+from flask import g
+from utility.db_tools import mescape
+from utility.db_tools import create_in_clause
 from wqflask.correlation.correlation_functions import get_trait_symbol_and_tissue_values
 from wqflask.correlation.correlation_gn3_api import create_target_this_trait
 from wqflask.correlation.correlation_gn3_api import lit_for_trait_list
@@ -12,6 +15,106 @@
 from gn3.db_utils import database_connector
 
 
+
+
+def chunk_dataset(dataset,steps,name):
+
+    results = []
+
+    query = """
+            SELECT ProbeSetXRef.DataId,ProbeSet.Name
+            FROM ProbeSet, ProbeSetXRef, ProbeSetFreeze
+            WHERE ProbeSetFreeze.Name = '{}' AND
+                  ProbeSetXRef.ProbeSetFreezeId = ProbeSetFreeze.Id AND
+                  ProbeSetXRef.ProbeSetId = ProbeSet.Id
+    """.format(name)
+
+    traits_name_dict = dict(g.db.execute(query).fetchall())
+
+
+    for i in range(0, len(dataset), steps):
+        matrix = list(dataset[i:i + steps])
+        trait_name = traits_name_dict[matrix[0][0]]
+
+        strains = [trait_name] + [str(value) for (trait_name, strain, value) in matrix]
+        results.append(",".join(strains))
+
+    breakpoint()

*nitpick:* Ideally, this: "breakpoint()",
shouldn't be in a commit.  One way to work around
this is to have a fix-up commit and then do an
auto-squash much later.

+    return results
+
+
+def compute_top_n_sample(start_vars, dataset, trait_list):

*nitpick*: Probably give this a better name.  What
does this mean?  Compute top n sample of what?

+    """only if dataset is of type probeset"""
+

*nitpick*: Also use better more descriptive
 docstrings.  I see you've made an attempt at this
 in fa8ef3e466e3919648e1d4cf9c38ed30328fc7a6.
 More comments there later.

[...]

+
+    ty = __fetch_sample_ids__(start_vars["sample_vals"], start_vars["corr_samples_group"])
+

*nitpick:* "ty" is an awful name to use.
 Moreover...

+
+
+    with database_connector() as conn:
+
+        curr = conn.cursor()
+
+        curr.execute(
+
+        """
+            SELECT * from ProbeSetData
+            where StrainID in {}
+            and id in (SELECT ProbeSetXRef.DataId
+            FROM (ProbeSet, ProbeSetXRef, ProbeSetFreeze)
+            WHERE ProbeSetXRef.ProbeSetFreezeId = ProbeSetFreeze.Id
+            and ProbeSetFreeze.Name = '{}'
+            and ProbeSet.Name in {}
+            and ProbeSet.Id = ProbeSetXRef.ProbeSetId)
+           """.format(create_in_clause(list(ty.values())),dataset.name,create_in_clause(trait_list))
+

... since it's only used once, you could pass that in directly above.
Don't give yourself the burden of naming when you
can avoid altogether.  You can ignore this remark
since it's already addressed in: fa8ef3e466e3919648e1d4cf9c38ed30328fc7a6

+
+        )
+
+
+
+
+        return chunk_dataset(list(curr.fetchall()),len(ty.values()),dataset.name)
+
+

*nitpick:* There's a lot of dead white-space that
you should remove.  Similar to the previous
comment, for superflous changes, create a fix-up
commit and then later auto-squash.

[...]

+
+
+    results = compute_top_n_sample(start_vars,target_dataset,list(results.keys()))
+
+
+
+    breakpoint()
+

See above comment on fix-up commits.

[...]

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
---
 .../wqflask/correlation/rust_correlation.py   | 69 ++++++++++---------
 1 file changed, 38 insertions(+), 31 deletions(-)

diff --git a/wqflask/wqflask/correlation/rust_correlation.py b/wqflask/wqflask/correlation/rust_correlation.py
index 94720f547..2a2ad4a0f 100644
--- a/wqflask/wqflask/correlation/rust_correlation.py
+++ b/wqflask/wqflask/correlation/rust_correlation.py
@@ -39,15 +39,14 @@ def chunk_dataset(dataset,steps,name):
         strains = [trait_name] + [str(value) for (trait_name, strain, value) in matrix]
         results.append(",".join(strains))
 
-    breakpoint()
     return results
 
 
 def compute_top_n_sample(start_vars, dataset, trait_list):
-    """only if dataset is of type probeset"""
-
-
+    """check if dataset is of type probeset"""
 
+    if dataset.type!= "Probeset":

*nitpick:* should be:

     if dataset.type != "Probeset":

[Note the space around the operand].

Also, the doc-string is a redundant: You literally
describe compute_top_n_sample and:

    if dataset.type != "Probeset": 

with

    "check if dataset is of type probeset"

[...]
+        #fetching strain data in bulk
+

*nitpick:* This should be   "# fetching ...".  Note the space after "#".

[...]

+
+            #currently fails for lit
+

*nitpick*: Have spaces after '#'.  Again, perhaps
 integrate into your workflow one of the many
 linters (python-black, flake8, python-autopep8,
 etc etc)

[...]

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
---
 wqflask/wqflask/correlation/rust_correlation.py | 11 ++++++++---
 1 file changed, 8 insertions(+), 3 deletions(-)

diff --git a/wqflask/wqflask/correlation/rust_correlation.py b/wqflask/wqflask/correlation/rust_correlation.py
index 2a2ad4a0f..ce1b5fda3 100644
--- a/wqflask/wqflask/correlation/rust_correlation.py
+++ b/wqflask/wqflask/correlation/rust_correlation.py
@@ -1,7 +1,6 @@
 """module contains integration code for rust-gn3"""
 import json
 from functools import reduce
-from flask import g
 from utility.db_tools import mescape
 from utility.db_tools import create_in_clause
 from wqflask.correlation.correlation_functions import get_trait_symbol_and_tissue_values
@@ -29,8 +28,12 @@ def chunk_dataset(dataset,steps,name):
                   ProbeSetXRef.ProbeSetId = ProbeSet.Id
     """.format(name)
 
-    traits_name_dict = dict(g.db.execute(query).fetchall())
+    with database_connector() as conn:
+        curr = conn.cursor()
 
+        curr.execute(query)
+
+        traits_name_dict = curr.fetchall()
 
     for i in range(0, len(dataset), steps):
         matrix = list(dataset[i:i + steps])
@@ -45,7 +48,7 @@ def chunk_dataset(dataset,steps,name):
 def compute_top_n_sample(start_vars, dataset, trait_list):
     """check if dataset is of type probeset"""
 
-    if dataset.type!= "Probeset":
+    if dataset.type.lower()!= "probeset":

*nitpick:* Add a space around your operands.
 Perhaps configure you're editor to run auto-pep8
 or black?


         return  {}
 
     def __fetch_sample_ids__(samples_vals, samples_group):
@@ -248,6 +251,8 @@ def compute_correlation_rust(
 
     top_a = top_b = {}
 
+    compute_all  =  True
+

*nitpick:* Probably use a better name for values
 that store boolean values.  Perhaps,
 "should_compute_all"?

[...]
-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by Alexanderlacuna** [comment]
@BonfaceKilz  thanks for the review made the changes recommended

**Comment by BonfaceKilz** [comment]
Alexander Kabui ***@***.***>
aliandika:

> @BonfaceKilz  thanks for the review made the changes recommended
>
Thanks

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Review by fredmanglis — COMMENTED** [review]
I'm not sure about the correctness of this - I don't fully understand statistics - but I think a correlation of zero has a specific meaning in statistics, and therefore, providing such a default might be in error.

For now, I will merge as is.

**Review by fredmanglis — COMMENTED** [review]
*nitpick*: The extraneous whitespace makes it for annoying reading. One has to move their eyes too far and scroll a lot. In the future, avoid lots of empty lines, especially for related statement.

**Review by fredmanglis — COMMENTED** [review]
Don't do:

```python
    with database_connector() as conn:
        curr = conn.cursor()
```
instead, do:

```python
    with database_connector() as conn:
        with conn.cursor() as curr:
```

I will fix this for now, but keep that in mind. Ensure to put both the connection and cursor under the purview of context managers

**Review by fredmanglis — COMMENTED** [review]
String interpolation for queries is a really bad idea, e.g.
```python
 curr.execute(
                """
                    SELECT Strain.Name, Strain.Id FROM Strain, Species
                    WHERE Strain.Name IN {}
                    and Strain.SpeciesId=Species.Id
                    and Species.name = '{}'
                    """.format(create_in_clause(list(sample_data.keys())),
                               *mescape(dataset.group.species))

            )
```

**WHY?**: *SQL Injection* attacks

You probably want to rewrite the code above into something like:

```python
 sample_data_args = tuple(sample_data.keys())
 curr.execute(
                """
                    SELECT Strain.Name, Strain.Id FROM Strain, Species
                    WHERE Strain.Name IN ({})
                    and Strain.SpeciesId=Species.Id
                    and Species.name = %s
                    """.format(", ".join(["%s"] * len(sample_data_args))),
                   (sample_data_args + (dataset.group.species,) ))
```

**NOTE**: The above "correction" might not be correct - this was a top-of-the-head example to show the separation.

You want to provide placeholders in the query for all the data items necessary, and then a tuple of all the arguments to the query.

The database driver/library will do the appropriate escaping of the values.

I'll merge it as is for now, but we need to fix that in the next few days.

**Comment by fredmanglis** [comment]
@Alexanderlacuna @BonfaceKilz I have merged this to **testing**. Now to test that it all works.

**Comment by zsloan** [comment]
> String interpolation for queries is a really bad idea, e.g.
> 
> ```python
>  curr.execute(
>                 """
>                     SELECT Strain.Name, Strain.Id FROM Strain, Species
>                     WHERE Strain.Name IN {}
>                     and Strain.SpeciesId=Species.Id
>                     and Species.name = '{}'
>                     """.format(create_in_clause(list(sample_data.keys())),
>                                *mescape(dataset.group.species))
> 
>             )
> ```
> 
> **WHY?**: _SQL Injection_ attacks
> 
> You probably want to rewrite the code above into something like:
> 
> ```python
>  sample_data_args = tuple(sample_data.keys())
>  curr.execute(
>                 """
>                     SELECT Strain.Name, Strain.Id FROM Strain, Species
>                     WHERE Strain.Name IN ({})
>                     and Strain.SpeciesId=Species.Id
>                     and Species.name = %s
>                     """.format(", ".join(["%s"] * len(sample_data_args))),
>                    (sample_data_args + (dataset.group.species,) ))
> ```
> 
> **NOTE**: The above "correction" might not be correct - this was a top-of-the-head example to show the separation.
> 
> You want to provide placeholders in the query for all the data items necessary, and then a tuple of all the arguments to the query.
> 
> The database driver/library will do the appropriate escaping of the values.
> 
> I'll merge it as is for now, but we need to fix that in the next few days.

Is the issue here specifically with the IN clause (with the important part of the improvement being to have it in a tuple, which seems like it would prevent an injection attack)? What is the importance of the change from **Species.name = '{}'** to **Species.name = %s** ? Is that also related to an injection attack, or is it just because of the escaping being unnecessary?

**Comment by fredmanglis** [comment]
> Is the issue here specifically with the IN clause

Not specifically - the issue is both in the **IN** clause and in the **Species.name**

> What is the importance of the change from Species.name = '{}' to Species.name = %s

The **%s** is a placeholder in the query/prepared statement that tells the database driver, "A value will be provided for this placeholder, and what we want is for you to handle it appropriately".

The values are then provided in a tuple, with each **%s** placeholder expecting an actual value in the tuple, in the order of the placeholders.

-----

There is another placeholder format: **%(text)s**: This one expects you to provide a dictionary as the args - a pseudocode example:

```python
query = "SELECT * FROM some_table WHERE avalue = %(first)s AND anothervalue=%(second)s"
cursor.execute(query, {"first": "val1", "second": "val2"})
...
```

for more on how these placeholders work, have a look at the **paramstyle** explanation [here](https://mysqlclient.readthedocs.io/user_guide.html#functions-and-attributes).

**Comment by BonfaceKilz** [comment]
Muriithi Frederick Muriuki
***@***.***> aliandika:

> @fredmanglis commented on this pull request.
>
> I'm not sure about the correctness of this - I don't fully understand statistics - but I think a correlation of zero has a specific meaning in statistics, and therefore, providing such a default might be in error.
>

FWIW correlation shows a relationship between 2
random variables.  Zero correlations implies
noise IIUC.

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
zsloan ***@***.***> aliandika:

[...]

> Is the issue here specifically with the IN clause (with the important part of the improvement being to have it in a tuple, which seems like it would prevent an injection attack)? What is the importance of the change from **Species.name = '{}'** to **Species.name = %s** ? Is that also related to an injection attack, or is it just because of the escaping being unnecessary?
>

The problem with "Species.name = '{}'" is that you
pass the name directly to the engine.  No escaping
happens.  To work around this, you should pass
variables as named parameters, which will _force_
the database to use the specified type and value
of what you passed when executing the query;
thereby offering protection from Python SQL
injection.

More examples follow (from
<https://realpython.com/prevent-python-sql-injection/>):

    # BAD EXAMPLES. DON'T DO THIS!
    cursor.execute("SELECT admin FROM users WHERE username = '" + username + '");
    cursor.execute("SELECT admin FROM users WHERE username = '%s' % username);
    cursor.execute("SELECT admin FROM users WHERE username = '{}'".format(username));
    cursor.execute(f"SELECT admin FROM users WHERE username = '{username}'");


    # SAFE EXAMPLES. DO THIS!
    cursor.execute("SELECT admin FROM users WHERE username = %s'", (username, ));
    cursor.execute("SELECT admin FROM users WHERE username = %(username)s", {'username': username});

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by Alexanderlacuna** [comment]
@fredmanglis  on the issue having default 0 correlation you are correct,as the results have  nothing to do with
correlation computation but  not doing top  sample correlation for non probeset types/or cases where we set should compute all to false, hence missing the p_val and correlation value keys.There is a better 
approach maybe by setting a default string value meaning no computation happened.
wIll fix this in  a different pr.

**Comment by zsloan** [comment]
Oh, that makes sense! I think there might be other queries with this
problem in GN2.

**Pull request merged**
