### PR TITLE
Feature/fetch md files from gh docs repo

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR:
- Uses markdown files from: https://github.com/genenetwork/genenetwork2/blob/testing/wqflask/wqflask/static/markdown/glossary.md
- Replaces python-mistune with python-markdown(associated change on guix-bioinformatics [here](http://git.genenetwork.org/guix-bioinformatics/guix-bioinformatics/pulls/1))

#### How should this be tested?

Please checkout the glossary page (temporarily) set up [here](http://gn2-test1.genenetwork.org/glossary/) on Penguin2

#### Any background context you want to provide?

Replaced mistunes with markdown. PR [here](http://git.genenetwork.org/guix-bioinformatics/guix-bioinformatics/pulls/1)

#### What are the relevant pivotal tracker stories?

N/A

#### Screenshots (if appropriate)

N/A

#### Questions

@pjotrp or @Millak On penguin2 should I just comment out the vim input since it causes build failures?

### CODE REVIEW

**Comment by Alexanderlacuna** [comment]
@BonfaceKilz  Awesome

**Review by Alexanderlacuna — APPROVED** [review]
LGTM!

**Review by zsloan — APPROVED** [review]
dataclasses is pretty neat!

**Comment by BonfaceKilz** [comment]
zsloan <notifications@github.com> writes:

> @zsloan approved this pull request.
>
> dataclasses is pretty neat!

Yep! Though still not a big fan of classes. I'd
use dataclasses instead of named tuples or classes
with the @property field set.

-- 
Bonface M. K. <https://www.bonfacemunyoki.com>
Chief Emacs Bazu / Rieng ya software sare
Mchochezi of: <https://upbookclub.com> / Twitter: @BonfaceKilz
GPG Key: D4F09EB110177E03C28E2FE1F5BBAE1E0392253F

**Comment by BonfaceKilz** [comment]
To fix this [failing test](https://github.com/genenetwork/genenetwork2/runs/1432294939), I updated our docker image on dockerhub to contain the markdown lib. Also, once guix upstream comes up with an "ofiicial" docker image, I'll update our CI to use that, then when we change libs, we just have to do a guix update with the latest hash in a yml file(instead of modifying an image) :)

@Alexanderlacuna, you could use this PR as a demo of the md work that's to come ;)

**Pull request merged**
