### PR TITLE
Feature/add group management

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR adds new endpoints for adding groups.

#### How should this be tested?

N/A

#### Any background context you want to provide?

N/A
#### What are the relevant pivotal tracker stories?

(https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/authorisation.gmi)

#### Screenshots (if appropriate)
N/A

#### Questions

[N/A]

### CODE REVIEW

**Comment by zsloan** [comment]
After updating the guix profile I'm getting an import error for "from gn3.authentication import get_groups_by_user_uid"

Is that from some change that still needs to be merged into GN3? Don't see it in the current gn3.authentication

**Review by pjotrp — COMMENTED** [review]
Looking great!

**Comment by BonfaceKilz** [comment]
zsloan ***@***.***> anaandika:

> After updating the guix profile I'm getting an
> import error for "from gn3.authentication import
> get_groups_by_user_uid"
>
> Is that from some change that still needs to be merged into GN3? Don't see it in the current gn3.authentication

Yup. I've updated gn3 with those functions.

-- 
Bonface M. K.
D4F09EB110177E03C28E2FE1F5BBAE1E0392253F (hkp://keys.gnupg.net)
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by BonfaceKilz** [comment]
Going ahead to merge this.  There are some things that need to be ironed out-- that'll be done in some new PR.

**Pull request merged**
