### PR TITLE
Testing rm bloat (jqplot and ckeditor)

### PR DESCRIPTION
**Pull request by pjotrp**
Hi Zach, jqplot and ckeditor are not used, so we should remove them. ckeditor pretends to edit help pages etc., but it is not functional. 

Javascript packages should come in from Guix (like we do with the twitter feed). I am going to move the ones we use today across. Trying to move all non-source-code out of our tree.

### CODE REVIEW

**Comment by pjotrp** [comment]
We'll go one at a time with some time for testing. Not to confuse things too much. If anyone shouts I will re-add a package through Guix. Guix makes it much easier to deal with versioning. Besides it is more secure (an immutable resource).

**Comment by pjotrp** [comment]
See also #135

**Comment by zsloan** [comment]
I think this is okay; I also can't find anywhere that should need jqplot or ckeditor (I think the former was for some plot that may have been converted to plotly or the library Lei is using for the correlation scatterplot, and the latter may have been for editing html pages or something but doesn't seem to be in use now). Should I merge to testing and try it on my branch (and then staging if it seems to not be causing a problem there)?

**Comment by pjotrp** [comment]
Yup.

**Pull request merged**
