### PR TITLE
Feature/add upload api

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

Add endpoint for adding gzipped endpoint. To this enpoint you pass in a tar.gz file that contains the metadata and phenotype file.

#### How should this be tested?

`curl -F file=@upload-data.tar.gz http://localhost:5004/api/v_pre1/metadata/upload`

#### Any background context you want to provide?

Here's the spec: https://github.com/genenetwork/gn-docs/blob/master/api/upload.md

#### What are the relevant pivotal tracker stories?

On Trello

#### Screenshots (if appropriate)
N/A

#### Questions

N/A

### CODE REVIEW

**Review by pjotrp — COMMENTED** [review]
Can we use tmpdir instead of hard coded?

**Review by pjotrp — COMMENTED** [review]
What type of tests do we need to put in place?

**Comment by BonfaceKilz** [comment]
Pjotr Prins <notifications@github.com> writes:

> @pjotrp commented on this pull request.
>
> Can we use tmpdir instead of hard coded?

Yup!
-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by BonfaceKilz** [comment]
Pjotr Prins <notifications@github.com> writes:

> @pjotrp commented on this pull request.
>
> What type of tests do we need to put in place?

Unit tests are easiest for this. I'll break up the
side-effectful function and write tests for the
broken pieces; and then finally for the actual
end-point add an integration test where you mock
the request. Not hard to do IMHO; I've done that
before.

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by pjotrp** [comment]
Great. Let's add simple tests from the start. BTW I like the code. No hint of self :)

**Comment by zsloan** [comment]
This probably isn't important in terms of functionality, but it might make sense to set the directory using TEMPDIR from this file (just because that's where most other files get the temp directory, like gemma_mapping.py, etc) - https://github.com/genenetwork/genenetwork2/blob/testing/wqflask/utility/tools.py

**Comment by pjotrp** [comment]
> This probably isn't important in terms of functionality, but it might make sense to set the directory using TEMPDIR from this file (just because that's where most other files get the temp directory, like gemma_mapping.py, etc) - https://github.com/genenetwork/genenetwork2/blob/testing/wqflask/utility/tools.py

Yes, all global settings are handled through tools.py. We should rename that file ;)

**Comment by BonfaceKilz** [comment]
Closing this since it's already added in gn3

**Pull request closed without merging**
