### PR TITLE
chores/textfiles-improvement

### PR DESCRIPTION
**Pull request by Alexanderlacuna**
to reduce to time it takes to  fetch the query  for datasets like exon dataset use already 
files in web/ProbeSetFreeze_DataMatrix   folder

note this is a temporary fix before migration to use of lmdb

todo:test

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
Alexander Kabui ***@***.***>
aliandika:

> to reduce to time it takes to  fetch the query  for datasets like exon dataset use already 
> files in web/ProbeSetFreeze_DataMatrix   folder
>
> note this is a temporary fix before migration to use of lmdb
>
Hopefully, I should be able to get some working
version by close of next week \m/\m/.

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by Alexanderlacuna** [comment]
@BonfaceKilz  do you have a guideline on how you intend to migrate things

**Comment by BonfaceKilz** [comment]
Alexander Kabui ***@***.***>
aliandika:

> @BonfaceKilz  do you have a guideline on how you intend to migrate things

I'll have to write that out and share that.  If I
don't do so by end of next week, please remind me.
ATM, I'm been doing a bunch of experimentation.

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Review by zsloan — APPROVED** [review]
I think it's okay to go ahead and merge this; the benefits outweigh the remaining issues (which seems to be that some datasets might have issues in their text files).

**Pull request merged**
