### PR TITLE
Delete dataTables and it's extensions from git

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR removes datatable extensions from guix since we now call it from guix. See: https://github.com/genenetwork/genenetwork2/pull/427, https://github.com/genenetwork/genenetwork2/pull/426, and https://github.com/genenetwork/genenetwork2/pull/423

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
@robwwilliams a bit of an OT, deletions like this one are what made the [PR](https://github.com/genenetwork/genenetwork2/pull/394) look pretty big(I remember you mentioning something like that in one of our meetings/ emails).

Also, @zsloan or @pjotrp you could merge this. It's pretty straightforward imo.

**Comment by pjotrp** [comment]
@zsloan can you merge this?

**Comment by BonfaceKilz** [comment]
Going ahead to merge this. It has no effect on the codebase.

**Comment by pjotrp** [comment]
Perfect!

**Pull request merged**
