### PR TITLE
Use one-step process for the partial correlations computations

### PR DESCRIPTION
**Pull request by fredmanglis**
This commit gets rid of the multi-step partial correlations process
replacing it with a single-step process.

Summary of changes:
* wqflask/wqflask/collect.py: Add function to format the trait details
  in a format that is usable for the partial correlations system.
* wqflask/wqflask/database.py: Provide function to create a connection
  to the database
* wqflask/wqflask/partial_correlations_views.py: Rework the code to
  enable the one-step process for the partial correlations
  computations
* wqflask/wqflask/static/new/javascript/partial_correlations.js: Get
  rid of code that supported the multi-step process
* wqflask/wqflask/templates/collections/view.html: Remove inconsistent
  UI elements. Attach traits info in a form usable for the partial
  correlations
* wqflask/wqflask/templates/partial_correlations.html: delete html
  template
* wqflask/wqflask/templates/partial_correlations/pcorrs_error.html:
  provide a html template to display errors in the partial
  correlations computation process
* wqflask/wqflask/templates/partial_correlations/pcorrs_poll_results.html:
  UI template to provide user with feedback as the computations
  continue in the background
* wqflask/wqflask/templates/partial_correlations/pcorrs_results_presentation.html:
  UI template to present the results of successful computation
* wqflask/wqflask/templates/partial_correlations/pcorrs_select_operations.html:
  UI template to trigger the partial correlations computations
* wqflask/wqflask/templates/tool_buttons.html: Add the partial
  correlations button to the template to ensure a consistent look and
  feel

#### Description

The changes here retain UI consistency, and also reduce the number of steps to compute the partial correlations.

In order to avoid timeouts in the webserver, and avoid the frequent messing with the webserver configurations, the changes here also provide for a polling system to check on the progress of the computation - this provides for a responsive service.

#### Dependencies

This code depends on [these changes to the API](https://github.com/genenetwork/genenetwork3/pull/81) to work as expected.

### CODE REVIEW

**Comment by fredmanglis** [comment]
@zsloan I have merged https://github.com/genenetwork/genenetwork3/pull/81 so please merge this to get it in front of the client, even as you update the data tables stuff

**Comment by fredmanglis** [comment]
@zsloan What's the word on this?

**Comment by zsloan** [comment]
It ended up taking me much longer than I thought to finish something else (
https://github.com/genenetwork/genenetwork2/pull/663 ), but I'm looking at
this now (though probably won't finish until tomorrow since it's getting
late).

Currently it's throwing an error within the __field_errors__ code for
partial_correlations and I'm not sure what the specific error is yet,
though I'm sure it won't work until I get sheepdog up (which still isn't
clear to me; I'll ask on the Element chat and tag Bonface), so it might
just be tied to that (though it's not clear from the error).

**Comment by fredmanglis** [comment]
@zsloan 

> Currently it's throwing an error within the __field_errors__ code for
> partial_correlations and I'm not sure what the specific error is yet,
> though I'm sure it won't work until I get sheepdog up

Well, the code in \_\_field_errors\_\_ does not depend on sheepdog running. If there is an error, share it here so that I can help debugging it.

In the meantime, I have merged the changes to **testing** - I need some of the changes therein to proceed.

**Comment by zsloan** [comment]
The 

> @zsloan
> 
> > Currently it's throwing an error within the **field_errors** code for
> > partial_correlations and I'm not sure what the specific error is yet,
> > though I'm sure it won't work until I get sheepdog up
> 
> Well, the code in __field_errors__ does not depend on sheepdog running. If there is an error, share it here so that I can help debugging it.
> 
> In the meantime, I have merged the changes to **testing** - I need some of the changes therein to proceed.

The error I'm getting there is the following:
```
File "/export2/local/home/zas1024/gn3-zach/genenetwork3/gn3/api/correlation.py", line 104, in __check__
    if args.get(field) is None:
AttributeError: 'str' object has no attribute 'get'
```

which actually seems kind of strange since I printed the args immediately beforehand and it printed as a dict:
```
{"primary_trait": {"trait_name": "1457545_at", "dataset": "HC_M2_0606_P", "description": "long non-coding RNA, expressed sequence tag (EST) AK035474 with high bladder expression; antisense EST 14 Kb upstream of Shh", "symbol": "9530036O11Rik", "location": "Chr5: 28.480441", "mean": "6.742", "lrs
": "12.100", "lrs_location": "Chr3: 9.983632"}, "control_traits": [{"trait_name": "1436869_at", "dataset": "HC_M2_0606_P", "description": "sonic hedgehog (hedgehog); mid distal 3' UTR", "symbol": "Shh", "location": "Chr5: 28.457155", "mean": "9.279", "lrs": "12.800", "lrs_location": "Chr1: 191.9
08117"}], "method": "Genetic Correlation, Pearson's r", "target_db": "BXDPublish", "criteria": "500"}
```

**Comment by fredmanglis** [comment]
@zsloan What commit of GN3 are you on? I think I fixed that a while back on branch **main**: it could be a regression, but make sure you have the latest on branch **main** for GN3, then let me know whether the issue shows up still.

**Comment by zsloan** [comment]
The most recent commit is a7696cc668e00215e1d5af2425765451811bca9d ("Remove
unused function and its tests")

**Comment by fredmanglis** [comment]
Hmm, that is interesting. I think that might be a regression. I will have a look and fix it,

**Comment by zsloan** [comment]
Changing the get_json line to the below* fixed the error (though there's probably some better way). Is there a way to check that sheepdog is working correctly (or if there's some other issue, like with Redis or something)? I ran it with "env python3 sheepdog/worker.py" and it didn't throw an error, but the correlations seem to be running indefinitely like before.

*
```
args = json.loads(request.get_json())
```

**Comment by zsloan** [comment]
Nevermind - it did finish! It just took a while (around 8 minutes when doing against BXD Phenotypes with one control trait). I'll go ahead and get it running on production now (with that one line above temporarily manually changed until you can look at it and decide what to do with it).

**Pull request merged**
