### PR TITLE
update  tests for run_gemma

### PR DESCRIPTION
**Pull request by Alexanderlacuna**
#### Description
modify tests for run_gemma

#### How should this be tested?
as unittest
#### Any background context you want to provide?

N/A

#### Screenshots (if appropriate)
N/A
#### Questions

N/A

### CODE REVIEW

**Review by BonfaceKilz — APPROVED** [review]
Much thanks for this. Actually ran into these failing tests in my branch and this seems to fix things

**Comment by zsloan** [comment]
Ah, I think this might have been a similar issue to the recent one I noticed with gemma_mapping.py (I had to change the way this_chromosomes was set).

**Comment by BonfaceKilz** [comment]
zsloan <notifications@github.com> writes:

> Ah, I think this might have been a similar issue
> to the recent one I noticed with gemma_mapping.py
> (I had to change the way this_chromosomes was
> set).

Yup and on point... I could see that bug was
introduced here:
7aaa4b87fcf405c32c11e2e2d664941c43c14430

-- 
Bonface M. K. <https://www.bonfacemunyoki.com>
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz
GPG Key: D4F09EB110177E03C28E2FE1F5BBAE1E0392253F

**Comment by pjotrp** [comment]
Is this a first with the new test system?

**Comment by BonfaceKilz** [comment]
Pjotr Prins <notifications@github.com> writes:

> Is this a first with the new test system?

Yup! I try to pay keen attention when sth is
refactored, but this one slipped my eye(probably
because that list comprehension made sense); but
was caught by @zsloan.

-- 
Bonface M. K. <https://www.bonfacemunyoki.com>
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz
GPG Key: D4F09EB110177E03C28E2FE1F5BBAE1E0392253F

**Comment by zsloan** [comment]
Yeah, I think the confusion was related to the Species class being really
weird. Species has a "chromosomes" attribute that is of the "Chromosomes"
class, but the "Chromosomes" class also has its own attribute which is also
called "chromosomes."

I feel like there isn't really any need for there to be a "Chromosomes"
class here, and that it could just be replaced by a function that returns
the list of chromosomes using either species or dataset as input.

**Comment by BonfaceKilz** [comment]
zsloan <notifications@github.com> writes:

> Yeah, I think the confusion was related to the Species class being really
> weird. Species has a "chromosomes" attribute that is of the "Chromosomes"
> class, but the "Chromosomes" class also has its own attribute which is also
> called "chromosomes."
>

Oof!

> I feel like there isn't really any need for there to be a "Chromosomes"
> class here, and that it could just be replaced by a function that returns
> the list of chromosomes using either species or dataset as input.
>

With time we'll clean those up. I optimistically
think we have a good momentum and we'll soon get
there IMHO :)

-- 
Bonface M. K. <https://www.bonfacemunyoki.com>
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz
GPG Key: D4F09EB110177E03C28E2FE1F5BBAE1E0392253F

**Pull request merged**
