### PR TITLE
Use NVD3 for bar chart and probability plot

### PR DESCRIPTION
**Pull request by lomereiter**
**Probability plot**
* Removed old `probability_plot.coffee/js` files
* Scatter plot from NVD3 is now used instead
* Shapiro-Wilk statistic and p-value are computed on client side (in Javascript), p-values less than .05 are highlighted in red

Example plot:
pp

**Bar chart**
* Changed rendering code to NVD3
* As in GN1, error bars are shown whenever SD is present

errorbars
* Also added tooltips that include sample name, value, SD and all attributes

tooltip

### CODE REVIEW

**Comment by robwwilliams** [comment]
Artem,

Great stuff. A slick interface will push adoption, and (god forbid) even
molecular biologists may learn a bit of stats.

We always use the SEM for the error term in GN rather than SD (but it would
be cool to eventually make this an option).



On Tue, May 26, 2015 at 9:39 AM, Artem Tarasov <notifications@github.com>
wrote:

> *Probability plot*
>
>    - Removed old probability_plot.coffee/js files
>    - Scatter plot from NVD3 is now used instead
>    - Shapiro-Wilk statistic and p-value are computed on client side (in
>    Javascript), p-values less than .05 are highlighted in red
>
> Example plot:
> [image: pp]
> <https://cloud.githubusercontent.com/assets/662555/7814851/76f8fdf8-03cd-11e5-99ba-d57d413955da.png>
>
> *Bar chart*
>
>    - Changed rendering code to NVD3
>    - As in GN1, error bars are shown whenever SD is present
>
> [image: errorbars]
> <https://cloud.githubusercontent.com/assets/662555/7814907/da00bdfa-03cd-11e5-8da7-804bf20a580e.png>
>
>    - Also added tooltips that include sample name, value, SD and all
>    attributes
>
> [image: tooltip]
> <https://cloud.githubusercontent.com/assets/662555/7814912/df9c9eaa-03cd-11e5-9a99-bb0e01d795ca.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/genenetwork/genenetwork2/pull/58
> Commit Summary
>
>    - new probability plot (using NVD3 library)
>    - Fix trait grouping
>    - fix group selection in blocking by index
>    - pp group selection
>    - use NVD3 for bar charts
>
> File Changes
>
>    - *M* wqflask/base/webqtlCaseData.py
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-0> (2)
>    - *M* wqflask/wqflask/show_trait/SampleList.py
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-1>
>    (45)
>    - *M* wqflask/wqflask/show_trait/show_trait.py
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-2>
>    (34)
>    - *M* wqflask/wqflask/static/new/css/bar_chart.css
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-3>
>    (10)
>    - *M* wqflask/wqflask/static/new/css/charts.css
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-4> (2)
>    - *M* wqflask/wqflask/static/new/css/show_trait.css
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-5> (4)
>    - *M* wqflask/wqflask/static/new/javascript/bar_chart.coffee
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-6>
>    (502)
>    - *M* wqflask/wqflask/static/new/javascript/bar_chart.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-7>
>    (580)
>    - *M*
>    wqflask/wqflask/static/new/javascript/draw_probability_plot.coffee
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-8>
>    (129)
>    - *M* wqflask/wqflask/static/new/javascript/draw_probability_plot.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-9>
>    (150)
>    - *D* wqflask/wqflask/static/new/javascript/probability_plot.coffee
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-10>
>    (424)
>    - *D* wqflask/wqflask/static/new/javascript/probability_plot.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-11>
>    (408)
>    - *M* wqflask/wqflask/static/new/javascript/scatterplot.coffee
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-12>
>    (2)
>    - *M* wqflask/wqflask/static/new/javascript/show_trait.coffee
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-13>
>    (44)
>    - *M* wqflask/wqflask/static/new/javascript/show_trait.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-14>
>    (62)
>    - *A* wqflask/wqflask/static/new/js_external/jstat.min.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-15>
>    (2)
>    - *A* wqflask/wqflask/static/new/js_external/shapiro-wilk.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-16>
>    (197)
>    - *A* wqflask/wqflask/static/new/packages/nvd3/nv.d3.css
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-17>
>    (641)
>    - *A* wqflask/wqflask/static/new/packages/nvd3/nv.d3.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-18>
>    (13362)
>    - *A* wqflask/wqflask/static/new/packages/nvd3/nv.d3.min.css
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-19>
>    (1)
>    - *A* wqflask/wqflask/static/new/packages/nvd3/nv.d3.min.js
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-20>
>    (8)
>    - *M* wqflask/wqflask/templates/show_trait.html
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-21>
>    (7)
>    - *M* wqflask/wqflask/templates/show_trait_edit_data.html
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-22>
>    (6)
>    - *M* wqflask/wqflask/templates/show_trait_statistics_new.html
>    <https://github.com/genenetwork/genenetwork2/pull/58/files#diff-23>
>    (33)
>
> Patch Links:
>
>    - https://github.com/genenetwork/genenetwork2/pull/58.patch
>    - https://github.com/genenetwork/genenetwork2/pull/58.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/pull/58>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604-4752
Office: 501 Wittenborg Building
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by lomereiter** [comment]
Thanks Rob, 

Indeed I got confused about the SD/SE, fixed it now.

**Comment by zsloan** [comment]
I tried merging the pull request, but it seems that the file prob_plot.css is missing when I tried to run it on my branch of GN2. Did you maybe forget to include this file?

This is a great improvement by the way; we've been wanting to to add some of these things to those figures for a while.

**Comment by lomereiter** [comment]
It was indeed missing, added it in https://github.com/lomereiter/genenetwork2/commit/e9f7904e0f5ef1fb7a421f376f145c337c69d7f5

**Comment by zsloan** [comment]
Artem, do you know if you can also use this library for histograms? I checked and noticed they weren't listed in the examples, but it seems like there isn't that much of a difference between the two aside from the use of bins (which is handled by d3.histogram). Ideally we could keep the style consistent between the histogram and the bar chart (just thought of this after creating the permutation histogram issue). Specifically the grey grid behind the bars and the different looking y axis come to mind.

**Comment by lomereiter** [comment]
Yes, I had this thought too. It shouldn't be difficult, I'll work on it.

**Pull request merged**
